# Generated by Django 4.0.1 on 2022-02-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='https://i.stack.imgur.com/y9DpT.jpg', null=True, upload_to=''),
        ),
    ]
